server:
  port: 9090

spring:
  redis:
    host: localhost
    port: 6379

zuul:
  RateLimitFilter:
    pre:
      disable: true
  routes:
    jsf:
      path: /jsf/**
      url: http://localhost:8180
      customSensitiveHeaders: true
      threshold: 10
      thresholdUnit: SECONDS
    cache:
      path: /cache/**
      url: http://localhost:8083
      customSensitiveHeaders: true
      threshold: 200
      thresholdUnit: MINUTES
  ratelimit:
    enabled: true
    repository: REDIS
    policy-list:
      jsf:
        - limit: 100
          refresh-interval: 1
          type:
            - origin
      cache:
        - limit: 200
          refresh-interval: 2
          type:
            - origin