server:
  port: 9090

spring:
  redis:
    host: localhost
    port: 6379
  data:
    redis:
      repositories:
        enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

zuul:
  SendErrorFilter:
    error:
      disable: true
  routes:
    jsf:
      path: /jsf/**
      url: http://localhost:8180
      customSensitiveHeaders: true
      threshold: 10
      thresholdUnit: SECONDS
    redis:
      path: /redis/**
      url: http://localhost:8280
      customSensitiveHeaders: true
      threshold: 200
      thresholdUnit: MINUTES