server:
  port: 9090

spring:
  data:
    redis:
      repositories:
        enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

elasticsearch:
  clustername: elasticsearch_keithkester
  host: localhost
  port: 9300

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: "always"

zuul:
  SendErrorFilter:
    error:
      disable: true
  SecurityFilter:
    pre:
      disable: false
  RequestIdFilter:
    pre:
      disable: false
  routes:
  ratelimit:
    enabled: false
    repository: REDIS
    policy-list:
