server:
  port: 9090

spring:
  data:
    redis:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    platform: mysql
    initialization-mode: always
    url: "jdbc:mysql://localhost:3306/db_example?verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimezone=UTC"
    username: "root"
    password: "yourpassword"

security:
  signing-key: MaYzkSjmkzPC57L
  security-realm: Spring Edge Service Realm

elasticsearch:
  clustername: elasticsearch_keithkester
  host: localhost
  port: 9300

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: "always"

zuul:
  SendErrorFilter:
    error:
      disable: true
  SecurityFilter:
    pre:
      disable: false
  RequestIdFilter:
    pre:
      disable: false
  routes:
  ratelimit:
    enabled: false
    repository: REDIS
    policy-list:
