spring:
  data:
    redis:
      repositories:
        enabled: false

application:
  integration:
    edge-service-app-host: ${edge_service_app_host}
    public-api-key: b14539f6ae4345f3a80d5b2a54550177